spring.application.name=backend

server.port=8080

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://${postgres.host:db2}:${postgres.port:5432}/${postgres.db:pick_me_db}
spring.datasource.username=${postgres.user:pick_me_user}
spring.datasource.password=${postgres.password:12345678}
spring.datasource.hikari.maximumPoolSize=95

# JPA & HIBERNATION CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
#spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# SECURITY
security.jwt.secret-key=3cd93bc24b84729ddcd507dfc4bb82a3cd211134243ca858d3c96e7e0b1b31d0b
security.jwt.expiration-time=900000
security.jwt.refresh-secret-key=210f098f5cb1c6c0817eb9c3fe554d58af7313d8f20b556d0f5e313d99a1a3b8
security.jwt.refresh-expiration-time=604800000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pick.me.official.mail@gmail.com
spring.mail.password=lllqkwpkwqcgfazc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# REDIS
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.database=0

spring.verification-code.ttl-minutes=10
