vaadin.launch-browser=true
spring.application.name=backend

server.port=8080

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://${postgres.host:localhost}:${postgres.port:5432}/${postgres.db:pick_me_db}
spring.datasource.username=${postgres.user:pick_me_user}
spring.datasource.password=${postgres.password:12345678}
spring.datasource.hikari.maximumPoolSize=95

# JPA & HIBERNATION CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#spring.jackson.serialization.fail-on-empty-beans=false

security.jwt.secret-key = 3cd93bc24b84729ddcd507dfc4bb82a3cd211134243ca858d3c96e7e0b1b31d0b
security.jwt.expiration-time = 3600000000
