spring.application.name=backend

server.port=8080

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pick_me_db}
spring.datasource.username=${POSTGRES_USER:pick_me_user}
spring.datasource.password=${POSTGRES_PASSWORD:12345678}
spring.datasource.hikari.maximumPoolSize=95

# JPA & HIBERNATION CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
#spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# SECURITY
security.jwt.secret-key=${JWT_SECRET_KEY:3cd93bc24b84729ddcd507dfc4bb82a3cd211134243ca858d3c96e7e0b1b31d0b}
security.jwt.expiration-time=900000
security.jwt.refresh-secret-key=${JWT_REFRESH_SECRET_KEY:210f098f5cb1c6c0817eb9c3fe554d58af7313d8f20b556d0f5e313d99a1a3b8}
security.jwt.refresh-expiration-time=604800000

# MAIL
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:pick.me.official.mail@gmail.com}
spring.mail.password=${MAIL_PASSWORD:lllqkwpkwqcgfazc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# REDIS
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.database=0

spring.verification-code.ttl-minutes=10

# FRONTEND
frontend.url=${FRONTEND_URL:http://localhost:4200}

# LOGS
logging.level.=INFO

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true