# DB connection
url=jdbc:postgresql://${POSTGRES_HOST:db2}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pick_me_db}
username=${POSTGRES_USER:pick_me_user}
password=${POSTGRES_PASSWORD:12345678}
driver=org.postgresql.Driver

# diff sources
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml